version: '3'
services:

  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
        jenkins:
          aliases:
            - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    command: --storage-driver overlay2
    profiles: ["service"]

  jenkins-blueocean:
    build: 
      context: .
      dockerfile: Dockerfile.service
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    profiles: ["service"]

  jenkins-agent:
    image: jenkins/inbound-agent:latest-jdk17
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles: ["agent"]
      
networks:
  jenkins:

volumes:
  agent-volume:
  jenkins-docker-certs:
  jenkins-data: